services:
  axie-studio:
    image: axiestudio/axie-studio:latest # or another version tag
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - AXIE_STUDIO_DATABASE_URL=postgresql://axiestudio:axiestudio@postgres:5432/axiestudio
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - AXIE_STUDIO_CONFIG_DIR=app/axie_studio
    volumes:
      - axie-studio-data:/app/axie_studio

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: axiestudio
      POSTGRES_PASSWORD: axiestudio
      POSTGRES_DB: axiestudio
    ports:
      - "5432:5432"
    volumes:
      - axie-studio-postgres:/var/lib/postgresql/data

volumes:
  axie-studio-postgres:
  axie-studio-data:
